---
title: "Professional Experiences"
---

I have worked in research as an intern or assistant in various settings since 2009. These roles have grounded me in community-engaged, qualitative, and ethics-focused work that directly informs my current PhD training in bioethics and health humanities.

# Summer Research Assistant

**Maxwell J. Mehlman, JD**\
Case Western Reserve University  

**Kim Kaphingst, ScD**\
University of Utah

In this role, I worked for a collaborative project between Case Western Reserve University and the University of Utah. My work has included conducting individual interviews with participants and helping to develop the codebook for qualitative analysis. This work deepened my thinking about nudging in research ethics and how to think through those considerations in my future work.

----

# Professional Research Assistant

**Katrina G. Claw, PhD**\
University of Colorado Anschutz Medical Campus

Working with Dr. Claw, I contribute to genomics and bioethics projects centered around my Tribe. My responsibilities have included literature review, qualitative coding, and manuscript preparation, as well as assisting with curriculum and materials for community-facing educational outreach. This work gave me experience in community-based participatory research, Tribal policy, and approaches that center Indigenous sovereignty and relational accountability in genomic science.

---

# Summer Intern and Post-Bac Fellow

**Sara Chandros Hull, PhD**\
National Institutes of Health, National Human Genome Research Institute, Tribal Health Research Office

With Dr. Hull and the Tribal Health Research Office at the NIH, I gained experience in how literature research supports broader projects focused on the ethics and governance of Tribal health research within U.S. federal government. My work has involved background research on policy and guidance documents, training in Institutional Review Board meetings, and contributions to public presentations and manuscripts. These experiences have given me a foundational view of how federal structures are trying to address Tribal priorities in health research, and how ethics can help push those structures toward respecting Tribal sovereignty.

---
